# -*- coding: utf-8 -*-
"""BreastUltrasoundYolov12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihEyVixy33y95MZjtbo76tKGor7d1hz-
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import subprocess
from google.colab import drive
import shutil # Import shutil for directory removal

class EnvironmentManager:
    @staticmethod
    def setup(project_base, repo_url="https://github.com/sunsmarterjie/yolov12.git"):
        print("--- Step 1: Setting up Environment ---")
        if not os.path.exists('/content/drive'):
            drive.mount('/content/drive')

        # Ensure project directory exists and navigate
        os.makedirs(project_base, exist_ok=True)
#         %cd {project_base}

        repo_dir = 'yolov12'
        # Check if the repository directory exists and is a valid git repository
        if os.path.exists(repo_dir):
            if os.path.isdir(os.path.join(repo_dir, '.git')):
                print(f"'{repo_dir}' already exists and is a git repository. Skipping clone.")
            else:
                print(f"'{repo_dir}' exists but is not a valid git repository. Removing and re-cloning.")
                shutil.rmtree(repo_dir) # Remove the problematic directory
                subprocess.run(["git", "clone", repo_url], check=True)
        else:
            print(f"Cloning '{repo_url}' into '{repo_dir}'...")
            subprocess.run(["git", "clone", repo_url], check=True)

#         %cd {repo_dir}

        # Recreate requirements.txt with original fixed versions
        with open("requirements.txt", "w") as f:
            f.write("torch==2.2.2\ntorchvision==0.17.2\ntimm==1.0.14\nalbumentations==2.0.4\n"
                    "pycocotools==2.0.7\nPyYAML==6.0.1\nscipy==1.13.0\nonnxslim==0.1.31\n"
                    "onnxruntime-gpu==1.18.0\ngradio==4.44.1\nopencv-python==4.9.0.80\n"
                    "psutil==5.9.8\npy-cpuinfo==9.0.0\nhuggingface-hub==0.23.2\n"
                    "safetensors==0.4.3\nnumpy==1.26.4\nsupervision==0.22.0\n")

        # Install dependencies and core tools
        subprocess.run(["pip", "install", "-q", "-r", "requirements.txt"], check=True)
        subprocess.run(["pip", "install", "-q", "-U", "pip", "setuptools", "wheel"], check=True)
        subprocess.run(["pip", "install", "-q", "--only-binary=:all:", "onnx==1.16.2"], check=True)
        subprocess.run(["pip", "install", "-q", "flash-attn==2.6.3", "--no-build-isolation"], check=True)
        subprocess.run(["pip", "install", "-q", "-e", "."], check=True)
        subprocess.run(["pip", "install", "-q", "-U", "ultralytics==8.3.176"], check=True)
        print("Environment setup complete.")

class YOLOv12Pipeline:
    """Modular training and inference engine with parameter abstraction."""
    def __init__(self, pretrained_weights):
        from ultralytics import YOLO
        self.model = YOLO(pretrained_weights)

    def train(self, config):
        print(f"--- Step 2: Training on {config['data']} ---")
        return self.model.train(**config)

    def predict(self, weight_path, img_path):
        from ultralytics import YOLO
        import cv2
        import numpy as np
        from matplotlib import pyplot as plt

        print(f"--- Step 3: Running Inference on {img_path} ---")
        inference_model = YOLO(weight_path)
        results = inference_model(img_path)

        for r in results:
            img = cv2.imread(img_path)
            # Apply Red Overlay Segmentation Masks
            if r.masks is not None:
                masks = r.masks.data.cpu().numpy()
                for mask in masks:
                    mask = (mask.astype(np.uint8) * 255)
                    colored_mask = np.zeros_like(img)
                    colored_mask[:, :, 2] = mask
                    img = cv2.addWeighted(img, 1.0, colored_mask, 0.5, 0)

            # Draw Bounding Boxes and Labels
            if r.boxes is not None:
                boxes = r.boxes.xyxy.cpu().numpy()
                scores = r.boxes.conf.cpu().numpy()
                class_ids = r.boxes.cls.cpu().numpy().astype(int)
                names = inference_model.names
                for box, score, cls_id in zip(boxes, scores, class_ids):
                    x1, y1, x2, y2 = map(int, box)
                    label = f"{names[cls_id]} {score:.2f}"
                    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
                    cv2.putText(img, label, (x1, max(y1 - 10, 0)),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

            plt.figure(figsize=(10, 10), dpi=300)
            plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
            plt.axis("off")
            plt.show()

def run_breast_cancer_analysis(execution_config):
    # Manage Environment (Side Effect Control)
    EnvironmentManager.setup(execution_config['project_base'])

    # Initialize Pipeline
    pipeline = YOLOv12Pipeline(execution_config['pretrained_weights'])

    # Execution Logic
    if execution_config['run_train']:
        pipeline.train(execution_config['train_params'])

    if execution_config['run_test']:
        pipeline.predict(
            weight_path=execution_config['best_weights'],
            img_path=execution_config['test_image']
        )

# --- CONFIGURATION---
config = {
    'project_base': '/content/drive/MyDrive/BREASTyolov12',
    'pretrained_weights': '/content/drive/MyDrive/BREASTyolov12/yolov12/yolov12l-seg.pt',
    'best_weights': '/content/drive/MyDrive/BREASTyolov12/yolov12/runs/segment/train/weights/best.pt',
    'test_image': '/content/drive/MyDrive/BREASTyolov12/test/images/benign-28-_png.rf.fecedd5bfed6240ed92513538cd48b00.jpg',
    'run_train': True,
    'run_test': True,
    'train_params': {
        'data': '/content/drive/MyDrive/BREASTyolov12/data.yaml',
        'epochs': 300,
        'patience': 10,
        'batch': 8,
        'imgsz': 640,
        'device': '0',
        'save': True,
        'lr0': 0.001,
        'lrf': 0.01,
        'warmup_epochs': 3,
        'augment': True,
        'optimizer': 'AdamW',
        'amp': True
    }
}

# --- SINGLE CELL INVOCATION ---
run_breast_cancer_analysis(config)